Repository nitlang/nit, pull requests merged in 2018-05, with the labels that each got.

#2632 No intrude rope stream
  lib/core/stream.nit
Labels: ok_will_merge

#2633 Read byte rewrite
  lib/bitmap/bitmap.nit
  lib/core/exec.nit
  lib/core/file.nit
  lib/core/stream.nit
Labels: ok_will_merge

#2638 model_collect: collect all modules from a package
  src/model/model_collect.nit
Labels: ok_will_merge

#2640 lib/msgpack: unify several cases for deserialization
  lib/msgpack/read.nit
Labels: ok_will_merge, tests_are_ok

#2642 Write byte updates
  lib/core/file.nit
  lib/core/stream.nit
  lib/libevent.nit
  lib/socket/socket.nit
  lib/websocket/websocket.nit
Labels: ok_will_merge

#2645 nitpick: do not warn in not explicitly required modules
  src/nitpick.nit
Labels: ok_will_merge

#2646 tests/nitunit: test that private methods are nitunited
  tests/sav/nitunit_args1.res
  tests/test_nitunit.nit
Labels: ok_will_merge

#2647 Remove the binary serialization service
  lib/binary/serialization.nit
  tests/sav/test_binary_deserialization.res
  tests/sav/test_binary_deserialization_alt1.res
  tests/sav/test_binary_deserialization_alt2.res
  tests/test_binary_deserialization.nit
Labels: ok_will_merge

#2643 lib/socket: fix socket_c documentation
  lib/socket/examples/socket_server.nit
  lib/socket/socket.nit
  lib/socket/socket_c.nit
Labels: ok_will_merge

#2651 pnacl: remove target and related projects
  contrib/online_ide/.gitignore
  contrib/online_ide/Makefile
  contrib/online_ide/README.md
  contrib/online_ide/package.ini
  contrib/online_ide/setup/mode-nit.js
  contrib/online_ide/setup/nit.js
  contrib/online_ide/sources/nit/pnacl_nit.nit
  contrib/online_ide/sources/nit_mode_for_ace/lib_ace_mode/nit.js
  contrib/online_ide/sources/nit_mode_for_ace/lib_ace_mode/nit_highlight_rules.js
  contrib/online_ide/www/css/jquery.terminal.css
  contrib/online_ide/www/css/style.css
  contrib/online_ide/www/favicon.ico
  contrib/online_ide/www/index.html
  contrib/online_ide/www/js/FileSaver.js
  contrib/online_ide/www/js/editor_configuration.js
  contrib/online_ide/www/js/functions.js
  contrib/online_ide/www/js/jquery.terminal-0.8.7.js
  contrib/online_ide/www/js/pnacl_js.js
  contrib/online_ide/www/pnacl/pnacl_nit.nmf
  lib/core/text/native.nit
  lib/pnacl/examples/converter/Makefile
  lib/pnacl/examples/converter/README.md
  lib/pnacl/examples/converter/converter.nit
  lib/pnacl/examples/converter/converter/index.html
  lib/pnacl/examples/converter/converter/js/functions.js
  lib/pnacl/examples/converter/converter/js/pnacl_js.js
  lib/pnacl/package.ini
  lib/pnacl/pnacl.nit
  share/man/nitc.md
  src/compiler/abstract_compiler.nit
  src/compiler/compiler.nit
  src/platform/pnacl.nit
  tests/turing.skip
Labels: ok_will_merge

#2654 share/man: update man page for nitweb
  share/man/nitweb.md
Labels: ok_will_merge

#2652 lib/ini: better output
  lib/ini/ini.nit
Labels: ok_will_merge

#2660 src/nit: remove unused primitive_types module
  src/interpreter/naive_interpreter.nit
  src/interpreter/primitive_types.nit
Labels: ok_will_merge

#2661 lib/actors: uniformize Makefile names with the rest of the Nit project
  lib/actors/examples/chameneos-redux/Makefile
  lib/actors/examples/fannkuchredux/Makefile
  lib/actors/examples/mandelbrot/Makefile
  lib/actors/examples/simple/Makefile
Labels: ok_will_merge, tests_are_ok

#2664 json: rename and improve the quick and easy `deserialize_json`
  lib/json/README.md
  lib/json/serialization_read.nit
Labels: ok_will_merge

#2668 lib/core/text: add memset to `CString`
  lib/core/text/native.nit
  tests/sav/test_memset.res
  tests/test_memset.nit
Labels: ok_will_merge

#2669 lib/crypto: add in-place xor cipher on CStrings
  lib/crypto/xor_ciphers.nit
  tests/sav/test_inplace_xor.res
  tests/test_inplace_xor.nit
Labels: need_review, tests_are_ok

#2671 android: remove the deprecated armeabi target platform
  src/platform/android.nit
Labels: ok_will_merge

#2672 docker: nitpm requires libcurl, move it up from `full`
  misc/docker/Dockerfile
  misc/docker/full/Dockerfile
Labels: need_review, ok_will_merge

#2655 Added HTTP METHODS to CurlHTTPRequest
  lib/curl/curl.nit
  lib/curl/examples/curl_rest.nit
Labels: ok_will_merge

#2659 Bitmap fix missing checks
  lib/bitmap/bitmap.nit
Labels: ok_will_merge, tests_are_ok

#2675 macOS: skip one of the nitpm tests because of locale issues
  tests/Darwin.skip
Labels: need_review

#2676 Small improvements on the oot.sh script
  contrib/oot.sh
Labels: need_review

#2677 opportunity: add a docker-compose.yml file
  contrib/opportunity/docker-compose.yml
Labels: need_review

#2666 Trace system
  clib/traces.c
  clib/traces.h
  share/man/nitc.md
  src/compiler/abstract_compiler.nit
  src/compiler/separate_compiler.nit
Labels: need_review, tests_are_ok

#2673 doc/commands: introduce Markdown rendering for commands
  src/doc/commands/commands_md.nit
  src/doc/commands/tests/test_commands_md.nit
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ancestors.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_call.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_children.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_comment.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_descendants.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_entity.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_features.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_clone.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_contrib_file.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_contrib_file_content.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_contributors.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_desc.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_git.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_issues.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_license.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_license_file.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_license_file_content.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_ini_maintainer.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_lin.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_link.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_main_compile.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_mains.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_man_options.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_man_synopsis.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_mentities.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_new.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_param.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_parents.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_return.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_search.res
  src/doc/commands/tests/test_commands_md.sav/test_cmd_testing.res
Labels: ok_will_merge

#2683 contrib/nitiwiki: protect non-nit code blokcs in README
  contrib/nitiwiki/README.md
Labels: ok_will_merge, tests_are_ok

#2680 lib/core: remove BufferedReader
  lib/core/stream.nit
Labels: ok_will_merge

#2689 src/doc/commands: fix test class name for `commands_md`
  src/doc/commands/tests/test_commands_md.nit
Labels: ok_will_merge, tests_are_ok

#2692 lib/a_star: nitunitize tests
  lib/a_star/tests/test_a_star.nit
  tests/sav/test_a_star.res
  tests/test_a_star.nit
Labels: need_review, tests_are_ok

#2693 lib/base64: nitunize tests
  lib/base64/tests/test_base64.nit
  tests/sav/test_base64.res
  tests/test_base64.nit
Labels: need_review, tests_are_ok

#2694 lib/md5: nitunitize tests
  lib/md5/tests/test_md5.nit
  tests/sav/test_md5.res
  tests/test_md5.nit
Labels: need_review, tests_are_ok

#2697 nitpackage: check existence of README.md files
  share/man/nitpackage.md
  src/model/mpackage.nit
  src/nitpackage.nit
Labels: ok_will_merge, tests_are_ok

#2700 nitls: option -M escapes characters in paths
  src/nitls.nit
Labels: ok_will_merge, tests_are_ok

#2701 lib/core: Fix text tests
  lib/core/text/abstract_text.nit
Labels: ok_will_merge
