Repository nitlang/nit, pull requests merged in 2019-08, with the labels that each got.

#2777 MModule: new method `add_mclassdef` to avoid incoherent cache state.
  src/model/model.nit
Labels: ok_to_test, ok_will_merge

#2782 compiler: Refactored `AbstractRuntimeFunction`
  src/compiler/abstract_compiler.nit
  src/compiler/global_compiler.nit
  src/compiler/separate_compiler.nit
Labels: ok_to_test

#2783 mongodb: Fixed failing test for `aggregate` method.
  lib/mongodb/mongodb.nit
Labels: ok_to_test, ok_will_merge

#2773 Wrapper of ICU's UTF-16 encoded strings and conversion
  lib/core/text/u16_string.nit
Labels: ok_to_test, ok_will_merge, tests_are_ok

#2776 Adding a Windows build test
  .gitlab-ci.yml
Labels: ok_will_merge, tests_are_ok

#2785 Abstract_text: Add a method to get string representation of float in scientific notation
  lib/core/text/abstract_text.nit
Labels: ok_to_test, ok_will_merge, tests_are_ok
