Repository nitlang/nit, pull requests merged in 2019-07, with the labels that each got.

#2755 nitrpg: Move `nitrpg` to its own repository
  contrib/nitrpg/.gitignore
  contrib/nitrpg/Makefile
  contrib/nitrpg/README.md
  contrib/nitrpg/nitrpg.user.js
  contrib/nitrpg/package.ini
  contrib/nitrpg/src/achievements.nit
  contrib/nitrpg/src/events.nit
  contrib/nitrpg/src/events_generator.nit
  contrib/nitrpg/src/game.nit
  contrib/nitrpg/src/listener.nit
  contrib/nitrpg/src/reactors.nit
  contrib/nitrpg/src/statistics.nit
  contrib/nitrpg/src/templates/panels.nit
  contrib/nitrpg/src/templates/templates.nit
  contrib/nitrpg/src/templates/templates_base.nit
  contrib/nitrpg/src/templates/templates_events.nit
  contrib/nitrpg/src/test_achievements.nit
  contrib/nitrpg/src/test_events.nit
  contrib/nitrpg/src/test_game.nit
  contrib/nitrpg/src/test_helper.nit
  contrib/nitrpg/src/test_listener.nit
  contrib/nitrpg/src/test_statistics.nit
  contrib/nitrpg/src/web.nit
  contrib/nitrpg/www/styles/main.css
Labels: ok_to_test

#2739 ci: basic bench with old branch
  .gitlab-ci.yml
  benchmarks/bench_old.sh
Labels: ok_to_test, ok_will_merge

#2760 typing: get_method refactoring
  src/semantize/typing.nit
Labels: ok_to_test, ok_will_merge

#2763 nitc: fix --keep-going in the compiler broken by 539ca148d
  src/compiler/abstract_compiler.nit
  tests/nit.args
  tests/nitc.args
  tests/niti.skip
  tests/nitvm.skip
  tests/sav/nit_args9.res
  tests/sav/nitc_args12.res
Labels: ok_to_test, ok_will_merge

#2767 metrics: ReadmeMetrics uses markdown2
  src/metrics/readme_metrics.nit
  tests/sav/nitmetrics_args3.res
Labels: ok_to_test, ok_will_merge

#2768 doc: Rename `synopsys` into `synopsis`
  share/nitdoc/css/nitdoc.css
  share/nitweb/stylesheets/nitlight.css
  share/nitweb/stylesheets/nitweb.css
  src/doc/templates/html_model.nit
  src/doc/templates/term_model.nit
  src/doc/templates/tests/test_html_commands.sav/test_cmd_ancestors.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_call.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_children.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_comment.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_descendants.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_mains.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_mentities.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_parents.res
  src/doc/templates/tests/test_html_commands.sav/test_cmd_search.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_ancestors.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_call.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_children.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_descendants.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_entity.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_features.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_mains.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_mentities.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_parents.res
  src/doc/templates/tests/test_json_commands.sav/test_cmd_search.res
  src/doc/templates/tests/test_json_model.sav/test_classdefs_to_full_json.res
  src/doc/templates/tests/test_json_model.sav/test_classes_to_full_json.res
  src/doc/templates/tests/test_json_model.sav/test_groups_to_full_json.res
  src/doc/templates/tests/test_json_model.sav/test_modules_to_full_json.res
  src/doc/templates/tests/test_json_model.sav/test_packages_to_full_json.res
  src/doc/templates/tests/test_json_model.sav/test_propdefs_to_full_json.res
  src/doc/templates/tests/test_json_model.sav/test_props_to_full_json.res
  tests/sav/nitcatalog_args1.res
Labels: ok_will_merge

#2770 fix ci nitunit some
  .gitlab-ci.yml
Labels: ok_will_merge, tests_are_ok

#2771 ci: generate metrics output in an artifact file
  .gitlab-ci.yml
Labels: ok_will_merge, tests_are_ok
