Repository nitlang/nit, pull requests merged in 2019-02, with the labels that each got.

#2729 lib/core: handling of plus (+) sign when using to_i with Text objects
  lib/core/text/abstract_text.nit
  lib/core/text/fixed_ints_text.nit
Labels: ok_will_merge, tests_are_ok

#2732 docker: add image for continuous integration (without nit)
  misc/docker/ci/Dockerfile
  misc/docker/ci/README.md
Labels: need_review

#2733 tests/base_autocast: workaround a gcc bug
  tests/base_autocast.nit
  tests/sav/base_autocast_alt2.res
Labels: ok_will_merge

#2734 lib&contrib: add some raw and nitish in READMEs
  contrib/model_viewer/README.md
  examples/calculator/README.md
  lib/app/README.md
  lib/gamnit/README.md
  lib/serialization/README.md
Labels: ok_will_merge
