Repository nitlang/nit, pull requests merged in 2020-03, with the labels that each got.

#2812 neo: Move neo node creation
  src/neo.nit
Labels: ok_to_test

#2813 modelize_property: Split the build_property method of AAttrPropdef
  src/frontend/serialization_model_phase.nit
  src/modelize/modelize_property.nit
Labels: ok_to_test, ok_will_merge

#2810 src/astbuilder: Add new nodes makers
  src/astbuilder.nit
Labels: need_review, ok_to_test, ok_will_merge

#2808 separate_compiler: Refactored class compilation
  src/compiler/separate_compiler.nit
  src/compiler/separate_erasure_compiler.nit
Labels: ok_to_test, ok_will_merge, tests_are_ok
